# https://github.com/marketplace/actions/automatic-releases

name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build & test"
        run: |
          echo "done!"
      - name: "Get current datetime"
        id: datetime
        run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H:%M:%S')"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release-${{ steps.datetime.outputs.datetime }}"
          prerelease: true
          title: "Development Build"
